### ISSUE TITLE
compiler fails to build via command line

### ISSUE THREAD

**Issue by Cokemonkey11** [peq/WurstScript#333]
Windows 7 x64, latest JDK, latest commit (f14f472657b004be2915e2dbaa898f625be86e44)

Following the compilation directions on README.markdown:

I execute `ant -buildfile build-wurst.xml compile > out.tmp` 

The build fails with the message:

> BUILD FAILED
> c:\Users\Blake\workspace\WurstScript\de.peeeq.wurstscript\build-wurst.xml:83: Compile failed; see the compiler error output for details.
> Total time: 7 minutes 59 seconds

and out.tmp contains:

https://gist.github.com/Cokemonkey11/b2af8fe9aa81f58220d5

I made a few small changes to fix the build: `git diff HEAD^ > compile-fix.diff`

which looks like:

https://gist.github.com/Cokemonkey11/595149d9a2ac8d7c2da3

**Comment by peq** [comment]
It works for me with `javac 1.8.0_25`, so I cannot really test other alternatives. Can you please try the change that I pushed now?

If that does not work, I can also go back to the old Java 1.7 style for this.

**Comment by blakehawkins** [comment]
This latest commit did not fix the issue, unfortunately.

For reference:

> $ java -version
> java version "1.8.0_31"
> Java(TM) SE Runtime Environment (build 1.8.0_31-b13)
> Java HotSpot(TM) 64-Bit Server VM (build 25.31-b07, mixed mode)

> $ javac -version
> javac 1.8.0_31

**Comment by peq** [comment]
Ok, I will try upgrading to that version as well. But it is kind of strange for Java to break source compatibility.

Did something change in the error message or is it still the same?

**Comment by Cokemonkey11** [comment]
> $ ant -buildfile build-wurst.xml compile > out.tmp

> BUILD FAILED
> c:\Users\Blake\workspace\WurstScript\de.peeeq.wurstscript\build-wurst.xml:83: Compile failed; see the compiler error output for details.

> Total time: 9 minutes 13 seconds

out.tmp: https://gist.github.com/Cokemonkey11/a2cee06af572416dc097

`$ diff out.tmp out_old.tmp`: https://gist.github.com/Cokemonkey11/10ea4c769d2608df7e71

**Comment by blakehawkins** [comment]
That fixed it.
